sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t hieubert/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true hieubert/react-test npm test

after_success:
  - docker build -t hieubert/multi-client-10-14  ./client
  - docker build -t hieubert/multi-nginx-10-14  ./nginx
  - docker build -t hieubert/multi-server-10-14  ./server
  - docker build -t hieubert/multi-worker-10-14  ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push hieubert/multi-client-10-14 
  - docker push hieubert/multi-nginx-10-14 
  - docker push hieubert/multi-server-10-14 
  - docker push hieubert/multi-worker-10-14 

  deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-415054150345
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY